version: '3.8'

volumes:
  magic_beans_new_local_postgres_data: {}
  magic_beans_new_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: magic_beans_new_local_django
    container_name: magic_beans_new_local_django
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8001:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: magic_beans_new_production_postgres
    container_name: magic_beans_new_local_postgres
    volumes:
      - magic_beans_new_local_postgres_data:/var/lib/postgresql/data
      - magic_beans_new_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: magic_beans_new_local_redis
